clc;
clear;

%% Load the file path and settings
% Select the correct file path
bag = rosbag("simplecontrol_windsimplesim_test_timing_2022-10-10-15-26-23.bag")
%%
bSel = select(bag,'Topic','drone_hovergames/state');
ts_hovergames_state= timeseries(bSel,...
           'Header.Stamp.Sec',...
           'Header.Stamp.Nsec',...
           'Twist.Twist.Linear.X',...
           'Twist.Twist.Linear.Y',...
           'Pose.Pose.Position.X',...
           'Pose.Pose.Position.Y',...
           'Pose.Pose.Orientation.X',...
           'Pose.Pose.Orientation.Y',...
           'Pose.Pose.Orientation.Z',...
           'Pose.Pose.Orientation.W');
bSel = select(bag,'Topic','drone_hovergames/state_prediction');
ts_hovergames_state_pred = timeseries(bSel,...
           'Header.Stamp.Sec',...
           'Header.Stamp.Nsec',...
           'Twist.Twist.Linear.X',...
           'Twist.Twist.Linear.Y',...
           'Pose.Pose.Position.X',...
           'Pose.Pose.Position.Y',...
           'Pose.Pose.Orientation.X',...
           'Pose.Pose.Orientation.Y',...
           'Pose.Pose.Orientation.Z',...
           'Pose.Pose.Orientation.W');
bSel = select(bag,'Topic','/mavros/local_position/odom');
ts_mavros_state = timeseries(bSel,...
           'Header.Stamp.Sec',...
           'Header.Stamp.Nsec',...
           'Twist.Twist.Linear.X',...
           'Twist.Twist.Linear.Y',...
           'Pose.Pose.Position.X',...
           'Pose.Pose.Position.Y');
bSel = select(bag,'Topic','/mavros/setpoint_raw/target_attitude');
ts_mavros_attitude = timeseries(bSel,...
           'Header.Stamp.Sec',...
           'Header.Stamp.Nsec',...
           'Orientation.X',...
           'Orientation.Y',...
           'Orientation.Z',...
           'Orientation.W');
bSel = select(bag,'Topic','/mavros/setpoint_position/local');
ts_mavros_setpoint = timeseries(bSel,...
           'Header.Stamp.Sec',...
           'Header.Stamp.Nsec',...
           'Pose.Position.X');

%% Look at the data 
t_hovergames_state = readtime(ts_hovergames_state);
t_hovergames_state_pred = readtime(ts_hovergames_state_pred);
t_mavros_state = readtime(ts_mavros_state);
t_mavros_attitude = readtime(ts_mavros_attitude);
t_mavros_setpoint = readtime(ts_mavros_setpoint);
dt1 = t_hovergames_state(2)- t_hovergames_state(1)
dt2 = t_hovergames_state_pred(2)- t_hovergames_state_pred(1)
dt3 = t_mavros_state(2)- t_mavros_state(1)
dt4 = t_mavros_attitude(2)- t_mavros_attitude(1)
dt5 = t_mavros_setpoint(2)- t_mavros_setpoint(1)
%% Path of mavros and hovergames state 

figure(1)
plot(ts_mavros_state.Data(:,5), ts_mavros_state.Data(:,6), '-o')
hold on
plot(ts_hovergames_state.Data(:,5), ts_hovergames_state.Data(:,6), '-*')

%% Timing of the velocities

figure(2)
plot(t_hovergames_state, ts_hovergames_state.Data(:,4), '-o')
hold on
plot(t_mavros_state, ts_mavros_state.Data(:,4), '-*')

%% Timimng og the velocities plus the inuput
figure(2)
plot(t_hovergames_state, ts_hovergames_state.Data(:,3), 'r-o')
hold on
plot(t_mavros_state(1:4200), ts_mavros_state.Data(1:4200,3), 'g-*')
plot(t_mavros_attitude(1:880), ts_mavros_attitude.Data(1:880,3), 'b-*')
plot(t_mavros_setpoint, ts_mavros_setpoint.Data(:,3), 'c-s')
%% State versus state prediction 
figure(3)
plot(t_hovergames_state(2:end), ts_hovergames_state.Data(2:end,8), 'r-o')
hold on
plot(t_hovergames_state_pred(1:end-1), ts_hovergames_state_pred.Data(1:end-1,8), 'g-*')
plot(t_mavros_attitude, ts_mavros_attitude.Data(:,4), 'b-*')
%% Functions
function [time_sp] = readtime(timeseries_sp)
    time_sp = timeseries_sp.Data(:,1)+timeseries_sp.Data(:,2)*10^(-9);
end
